
#pragma once

#include <AP_HAL/AP_HAL_Boards.h>
#include <AP_CANManager/AP_CANSensor.h>

#ifndef HAL_WINGSENSOR_ENABLED
#define HAL_WINGSENSOR_ENABLED BOARD_FLASH_SIZE > 1024
#endif

#ifndef AP_WINGSENSOR_BACKEND_DEFAULT_ENABLED
#define AP_WINGSENSOR_BACKEND_DEFAULT_ENABLED HAL_WINGSENSOR_ENABLED
#endif

#ifndef AP_WINGSENSOR_ENABLED
#define AP_WINGSENSOR_ENABLED (HAL_MAX_CAN_PROTOCOL_DRIVERS && BOARD_FLASH_SIZE > 1024)
#endif

#ifndef AP_WINGSENSOR_CANOPEN_ENABLED
#define AP_WINGSENSOR_CANOPEN_ENABLED AP_WINGSENSOR_BACKEND_DEFAULT_ENABLED && HAL_MAX_CAN_PROTOCOL_DRIVERS
#endif

#define AP_CANOPEN_DEBUG 1
